apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: arm-high-memory-kwok
spec:
  disruption:
    consolidateAfter: 0s
    budgets:
      - nodes: 100%
  template:
    spec:
      nodeClassRef:
        group: karpenter.kwok.sh
        kind: KWOKNodeClass
        name: default
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.kwok.sh/instance-cpu
          operator: Gt
          values: ["8"]
        - key: karpenter.kwok.sh/instance-memory
          operator: Gt
          values: ["20000"]  # At least 16GB in MB
        - key: karpenter.kwok.sh/instance-family
          operator: In
          values: ["c", "m", "r"]  # Compute, General Purpose, and Memory-optimized